---
# Configuration for MCPShell with sandbox runner examples
#
# This configuration demonstrates how to use different runners for command execution,
# including the macOS sandbox-exec runner and Linux firejail for enhanced security.

mcp:
  tools:
    # Example 1: Simple hello world using default exec runner
    - name: hello_world
      description: Say hello to someone
      params:
        name:
          description: Name of the person to greet
          type: string
          required: true
      run:
        command: echo "Hello, {{.name}}!"

    # Example 2: Command using sandboxed runners
    - name: secure_echo
      description: Echo text in a sandboxed environment
      params:
        text:
          description: Text to echo
          type: string
          required: true
      run:
        command: 'echo "Sandboxed echo: {{.text}}"'
        runners:
          - name: sandbox-exec
            requirements:
              os: darwin
              executables: [sandbox-exec]
          - name: firejail
            requirements:
              os: linux
              executables: [firejail]

    # Example 3: Command execution in sandbox with restricted networking
    - name: network_check
      description: Try to access the network in a sandboxed environment
      params:
        url:
          description: URL to check (will fail)
          type: string
          required: true
      run:
        command: 'curl --max-time 5 {{.url}}'
        runners:
          - name: sandbox-exec
            requirements:
              os: darwin
              executables: [sandbox-exec, curl]
            options:
              allow_networking: false
          - name: firejail
            requirements:
              os: linux
              executables: [firejail, curl]
            options:
              allow_networking: false
      constraints:
        - 'true'

    # Example 4: File system access with restrictions
    - name: file_browser
      description: List files in a directory (with restrictions)
      params:
        directory:
          description: Directory to list
          type: string
          required: true
      constraints:
        - 'directory.matches("^/tmp|^/var/tmp")'
      run:
        command: 'ls -la {{.directory}}'
        runners:
          - name: sandbox-exec
            requirements:
              os: darwin
              executables: [sandbox-exec]
            options:
              allow_user_folders: false
              allow_read_folders:
                - "/tmp"
                - "/var/tmp"
          - name: firejail
            requirements:
              os: linux
              executables: [firejail]
            options:
              allow_user_folders: false
              allow_read_folders:
                - "/tmp" 
                - "/var/tmp"

    # Example 5: Custom sandbox profile with specific permissions
    - name: custom_sandbox
      description: Run with a custom sandbox profile
      params:
        command:
          description: Command to run
          type: string
          required: true
      run:
        command: '{{.command}}'
        runners:
          - name: sandbox-exec
            requirements:
              os: darwin
              executables: [sandbox-exec]
            options:
              allow_networking: false
              allow_user_folders: false
              custom_profile: |
                (version 1)
                (allow default)
                (deny network*)
                (allow file-read* (regex "^/tmp"))
          - name: firejail
            requirements:
              os: linux
              executables: [firejail]
            options:
              allow_networking: false
              allow_user_folders: false
              custom_profile: |
                # Firejail equivalent profile
                net none
                noroot
                whitelist /tmp
                read-only /tmp
      constraints:
        - 'command.matches("^ls|^pwd|^echo")'
